### ISSUE TITLE
Illegal value while building Stage 2 cluster install. 

### ISSUE THREAD

**Issue by nummysquee** [ClusterLabs/striker#102]
-=] Illegal value in 'AN::Tools::Readable->bytes_to_hr()' - Error Code 6 - Fatal Error - Readable.pm at 120 [=-

The passed byte size: [1952.5] contains an illegal value. Byte sizes can only be signed integers. It may also have commas in it which will be removed automatically.

Exiting.

**Comment by nummysquee** [comment]
Relevant snippet of striker.log

2016-10-11 15:43:44 - InstallManifest.pm 7013; [ Debug ] - Variables:
|- node: [wp-a01n01.warbyparker.com]
|- disk: [sda]
|- start: [44.5]
\- end: [1952]
2016-10-11 15:43:44 - InstallManifest.pm 7045; [ Debug ] - Variables:
|- node: [wp-a01n01.warbyparker.com]
|- disk: [sda]
|- type: [logical]
\- partition_size: [2048295666176]
2016-10-11 15:43:44 - InstallManifest.pm 7059; [ Debug ] - Variables:
|- node: [wp-a01n01.warbyparker.com]
|- disk: [sda]
**|- use_end: [1952.5]**
\- end: [1952]
2016-10-11 15:43:44 - Alert.pm 303; [ Entering: error() ] - <function takes no arguments>
2016-10-11 15:43:44: 
-=] Illegal value in 'AN::Tools::Readable->bytes_to_hr()' - Error Code 6 - Fatal Error - Readable.pm at 120 [=-

The passed byte size: [1952.5] contains an illegal value. Byte sizes can only be signed integers. It may also have commas in it which will be removed automatically.

Exiting.

**Comment by digimer** [comment]
I found the problem and I believe it's fixed in ad363c39505753e167db4f093b4f2acfbbd033fc. Can you patch InstallManigest.pm as per that commit to test it? If it works, close this bug please.

**Comment by digimer** [comment]
Closing. Re-open if you hit this again.
