### ISSUE TITLE
Check striker_tools.tar.bz != 0 bytes, else recreate archive.

### ISSUE THREAD

**Issue by nummysquee** [ClusterLabs/striker#103]
Ran into an issue where for some reason that I cannot recreate, striker_tools.tar.bz2 == 0 bytes. Checking the filesize and regenerating the file if the archive failed is a reasonable workaround.

**Comment by digimer** [comment]
OK, will do that next week when I am back in town. I'm going to tag this for pre v2.0.

Thanks for reporting!

**Comment by digimer** [comment]
I believe this was fixed in cca48f5ed9c761a2f3ee945ab9c00e01cf5ea302. Re-open if it happens again please.
