### ISSUE TITLE
binaries leaking into repo

### ISSUE THREAD

**Issue by victoredwardocallaghan** [ClusterLabs/striker#105]
$ find . -name '*' -exec file {} \; | grep ELF
./tools/check_dvd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=ae7ebff5c3310eeb931c5681aa12a7dc3c81056e, not stripped

**Comment by digimer** [comment]
Fixed, removed the binary.
