### ISSUE TITLE
Compilation error in ScanCore.pm 

### ISSUE THREAD

**Issue by nummysquee** [ClusterLabs/striker#107]
Results in striker web interface resulting in 'Internal Server Error'

from /var/log/httpd/error_log

> [Fri Nov 04 16:51:31 2016] [error] [client ::1] syntax error at /usr/share/perl5/AN/Tools/ScanCore.pm line 1185, near "];"
> [Fri Nov 04 16:51:31 2016] [error] [client ::1] syntax error at /usr/share/perl5/AN/Tools/ScanCore.pm line 1186, near "];"
> [Fri Nov 04 16:51:31 2016] [error] [client ::1] Compilation failed in require at /usr/share/perl5/AN/Tools.pm line 42.
> [Fri Nov 04 16:51:31 2016] [error] [client ::1] BEGIN failed--compilation aborted at /usr/share/perl5/AN/Tools.pm line 42.
> [Fri Nov 04 16:51:31 2016] [error] [client ::1] Compilation failed in require at /var/www/cgi-bin/striker line 31.
> [Fri Nov 04 16:51:31 2016] [error] [client ::1] BEGIN failed--compilation aborted at /var/www/cgi-bin/striker line 31.
> [Fri Nov 04 16:51:31 2016] [error] [client ::1] Premature end of script headers: striker
> [Fri Nov 04 16:51:33 2016] [error] [client ::1] syntax error at /usr/share/perl5/AN/Tools/ScanCore.pm line 1185, near "];"
> [Fri Nov 04 16:51:33 2016] [error] [client ::1] syntax error at /usr/share/perl5/AN/Tools/ScanCore.pm line 1186, near "];"
> [Fri Nov 04 16:51:33 2016] [error] [client ::1] Compilation failed in require at /usr/share/perl5/AN/Tools.pm line 42.
> [Fri Nov 04 16:51:33 2016] [error] [client ::1] BEGIN failed--compilation aborted at /usr/share/perl5/AN/Tools.pm line 42.
> [Fri Nov 04 16:51:33 2016] [error] [client ::1] Compilation failed in require at /var/www/cgi-bin/striker line 31.
> [Fri Nov 04 16:51:33 2016] [error] [client ::1] BEGIN failed--compilation aborted at /var/www/cgi-bin/striker line 31.
> [Fri Nov 04 16:51:33 2016] [error] [client ::1] Premature end of script headers: striker
> **[Fri Nov 04 16:51:35 2016] [error] [client ::1] syntax error at /usr/share/perl5/AN/Tools/ScanCore.pm line 1185, near "];"
> [Fri Nov 04 16:51:35 2016] [error] [client ::1] syntax error at /usr/share/perl5/AN/Tools/ScanCore.pm line 1186, near "];"
> [Fri Nov 04 16:51:35 2016] [error] [client ::1] Compilation failed in require at /usr/share/perl5/AN/Tools.pm line 42.
> [Fri Nov 04 16:51:35 2016] [error] [client ::1] BEGIN failed--compilation aborted at /usr/share/perl5/AN/Tools.pm line 42.**
> [Fri Nov 04 16:51:35 2016] [error] [client ::1] Compilation failed in require at /var/www/cgi-bin/striker line 31.
> [Fri Nov 04 16:51:35 2016] [error] [client ::1] BEGIN failed--compilation aborted at /var/www/cgi-bin/striker line 31.
> [Fri Nov 04 16:51:35 2016] [error] [client ::1] Premature end of script headers: striker
> `
>

**Comment by digimer** [comment]
This was fixed in the most recent commit.

**Comment by nummysquee** [comment]
Odd, I pulled from master.

**Comment by digimer** [comment]
I lied. I fixed it, but it looks like I haven't pushed it. I'll push in an hour or so.

**Comment by nummysquee** [comment]
Easiest fix ever

**Comment by digimer** [comment]
Pushed. Just replace ScanCore.pm.
