### ISSUE TITLE
Have a home button/link on all the web pages to take you to the first page

### ISSUE THREAD

**Issue by subu1962** [ClusterLabs/striker#13]
Some pages have a "back" arrow button and some others don't. It'll be good to have a "home" button/link on ALL the pages to start over the navigation.

**Comment by digimer** [comment]
I need to convert the back button from statically assigned to using the referred data. This shouldn't be too hard and I should be able to get it done for the next proper release.

Thanks for the suggestion!

**Comment by digimer** [comment]
Might be better to leave the 'Back' function as-is and simply add a 'Home' icon in the top left or top right whenever the 'cluster' CGI variable is set.

**Comment by digimer** [comment]
Removing this, the UI will be rebuilt entirely for v3 and v2 will be entering stable support.
