### ISSUE TITLE
scan-ipmitool: missing variable declarations

### ISSUE THREAD

**Issue by Tsu-ba-me** [ClusterLabs/striker#146]
About [this line](https://github.com/ClusterLabs/striker/commit/fc05a509055542c8c95ebc7ea3bc9fa5b3d6b262#r36343250) (line `849` in the current version of `scan-ipmitool`):
* `$variable_name` is initialized on line `848` of the old changes (left side on a split view)
* `$variable_uuid` is initialized on line `852` of the old changes

The agent is returning code `255` because this change is causing a compilation error.

Should the `insert_or_update_variables` call be removed or should the variable initialization be re-added?

**Comment by digimer** [comment]
Ooph, that's a bug. Fixing it now...

**Comment by digimer** [comment]
Fixed in dae02ecaf551f2f311fa0bb750a3bfc69b583802, thanks for reporting!
