### ISSUE TITLE
libvirt-guests need to be disabled when the virtual machines are managed by rgmanager

### ISSUE THREAD

**Issue by subu1962** [ClusterLabs/striker#74]
As per https://access.redhat.com/solutions/96543 "Why are my virtual machines managed by rgmanager being corrupted?"

If a virtual machine is autostarted or resumed when the service libvirt-guests starts then corruption can occur to any of those virtual machines if those virtual machines are managed by rgmanager. When the same virtual machine is running on multiple machines at the same time then corruption will occur.

The service libvirt-guests will auto start or resume virtual machines which can conflict with virtual machines that are managed by rgmanager.

**Comment by digimer** [comment]
This has been set to disable now, thank you for reporting!

**Comment by digimer** [comment]
Fixed in 955436d, closing.
