### ISSUE TITLE
libvirtd on a cluster node is stopped unexpectedly when rgmanager starts in RHEL 6

### ISSUE THREAD

**Issue by subu1962** [ClusterLabs/striker#75]
As per https://access.redhat.com/solutions/497513 

Issue

    When a cluster node is booted, libvirtd is started successfully by its init service, but then is stopped for some reason a short time later.
    rgmanager stops libvirtd

Resolution

Remove the libvirtd script resource from /etc/cluster/cluster.conf, and rely on the libvirtd service during boot to start the daemon:
Raw

# chkconfig libvirtd on

There is no need to have rgmanager start libvirtd; simply chkconfig it on on all nodes and let that handle starting the daemon.

**Comment by digimer** [comment]
I think I need to disagree with that finding, on the face of it (I am open to being argued out of this position). We once saw a case where a Fedora virt-manager client caused libvirtd on a node to crash. Back then, as per the issue you reference above, we did NOT manage the libvirtd service. So the daemon stayed off until a human fixed it.

In our testing (admittedly a year or so ago), we were able to restart libvirtd without impacting the hosted servers. Have you seen a case where a vm service was impacted by libvirtd being restarted? It *shouldn't*, given that libvirtd is not the hypervisor. At worst, I would expect rgmanager to mark the VM service as 'failed' but not actually turn off the VM.

**Comment by subu1962** [comment]
This issue was written not because we actually saw an issue such as the one
referenced above.

The issue we are trying to solve is the "frozen VM" issue and this is what
Red Hat recommended.

Subu

**Comment by digimer** [comment]
Given that altering how libvirtd works (and that it is under Anvil! management) would be a huge job. It's easy enough to remove it from the rgmanager section of cluster.conf and run tests directly without Striker (which would probably react poorly to not seeing the 'libvirtd_n0X' services), I am going to close this ticket for now. If your testing shows any correlation between libvirtd being managed then I am happy to revisit this.

Note; libvirtd is started before any servers are running, and it only is stopped during a withdrawl, which can't happen unless the server is migrated or off. So with the exception of a crash in libvirtd, there is no reason why the cluster should ever touch libvirtd except to query its status (/etc/init.d/libvirtd status), which should be perfectly harmless.
